project_id = "ozgghjbvhveswqplzegd"

[functions.save-image-to-storage]
verify_jwt = true

[functions.send-anniversary-reminders]
verify_jwt = false

[functions.analyze-cake-text]
verify_jwt = true

[functions.analyze-cake-photo]
verify_jwt = true

[functions.generate-complete-cake]
verify_jwt = true

[functions.generate-party-pack]
verify_jwt = true

[functions.send-welcome-email]
verify_jwt = true

[functions.generate-logo]
verify_jwt = true

[functions.create-razorpay-order]
verify_jwt = true

[functions.verify-razorpay-payment]
verify_jwt = true
